version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: login_app
    networks:
      - login-app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    
  redis:
    image: redis:7.4
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - login-app
    volumes:
      - redis_data:/data

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: login-app
    networks:
      - login-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_DB_HOST: postgres
      POSTGRES_DB_USER: adm
      POSTGRES_DB_PASSWORD: 123
      REDIS_HOST: redis-server

volumes:
  postgres_data:
  redis_data:

networks:
  login-app:
    driver: bridge
